### ISSUE TITLE
Support custom DNSDB server

### ISSUE THREAD

**Issue by emilstahl** [projectdiscovery/subfinder#706]
You should be able to set a custom passive DNS - DNSDB server in the config file.

To use CIRC.LU, SIE Europe etc as DNSDB source.

https://github.com/projectdiscovery/subfinder/blob/cf37fb438f3839c5a8bf7223afaff313e74aa7ee/v2/pkg/subscraping/sources/dnsdb/dnsdb.go#L43

**Comment by vzamanillo** [comment]
Subfinder uses sources instead of providers and every source is independent with his own properties (endpoint, authentication method...), it is a good idea having generic providers for standard DNS databases but IMO this would make hard to handle the configuration because it would have to handle multiple endpoints per provider, e.g:

```yaml
virustotal:
    - key
    - key
zoomeye: []
zoomeyeapi: []
fofa: []
fullhunt: []
generic_providers:
    dnsdb:
        url: url
        key: key
    circ.lu:
        url: url
        key: key
```

I think it's easier to add a new source per DNS database than to implement a new mechanism to make the changes to implement multi-provider management.
